project:
  type: website
  render:
    - "**/*.qmd"

website:
  favicon: docs/img/favicon-32x32.png
  title: "Ludovic Deneuville"
  navbar:
    background: "#AB8D3F"
    left:
      - href: index.qmd
        text: Home
      - text: IT Course
        menu:
          - href: https://ludo2ne.github.io/ENSAI-2A-complement-info/
            text: "IT complements (FR)"
            target: "_blank"
          - href: https://ludo2ne.github.io/ENSAI-2A-remise-a-niveau/
            text: "refresher course in Python, SQL, UML (FR)"
            target: "_blank"
      - text: Personal Projects
        menu:
          - href: "https://ludo2ne.github.io/Quarto-tuto"
            text: "Quarto tutorial"
            target: "_blank"
          - href: "https://github.com/ludo2ne/ENSAI-2A-projet-info-template"
            text: "Basic application"
            target: "_blank"
          - href: "https://ludo2ne.github.io/ENSAI-stats/"
            text: "Stat stuff (FR)"
            target: "_blank"
      - text: Hobbies
        menu:
          - href: docs/hobbies/landart.qmd
            text: "Land Art"
          - href: docs/hobbies/chess.qmd
            text: "Chess"
    right:
      - href: docs/bookmarks.qmd
        text: Helpful Resources
      - icon: github
        href: https://github.com/ludo2ne
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"}<br>
      [Source Code](https://github.com/ludo2ne/ludo2ne.github.io){.external target="_blank"}
  repo-url: https://github.com/ludo2ne/ludo2ne.github.io
  repo-branch: main
  reader-mode: true

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
