---
title: "My best chess games"
format: html
from: markdown+emoji
---

<link href="https://c2a.chesstempo.com/pgnviewer/v2.5/pgnviewerext.vers1.css" media="all" rel="stylesheet" crossorigin>
<script defer language="javascript" src="https://c1a.chesstempo.com/pgnviewer/v2.5/pgnviewerext.bundle.vers1.js" crossorigin></script>

<link
href="https://c1a.chesstempo.com/fonts/MaterialIcons-Regular.woff2"
rel="stylesheet" crossorigin>

<style>
.ct-pgn-viewer-multi-game-select {
    color: white;
    background-color: #AB8D3F;
}
</style>

<ct-pgn-viewer>
[Event `"`9th Open`"`]
[Site `"`La Fere FRA`"`]
[Round `"`7`"`]
[Date `"`2010.07.08`"`]
[White `"`Pisk, Petr`"`]
[Black `"`Deneuville, Ludovic`"`]
[WhiteElo `"`2337`"`]
[BlackElo `"`1968`"`]
[Result `"`1/2-1/2`"`]
1.e4 c5 2.Nf3 Nf6 3.Nc3 d5 4.exd5 Nxd5 5.Bb5+ Bd7 6.Ne5 Nf6 7.Nxd7 Nbxd7 8.d4 e6 9.Bg5 a6 10.Bxd7+ Qxd7 11.dxc5 Qxd1+ 12.Rxd1 Bxc5 13.Bxf6 gxf6 14.Ne4 Be7 15.Nd6+ Bxd6 16.Rxd6 Rc8 17.c3 Ke7 18.Rb6 Rc7 19.Ke2 Rd8 20.Rd1 Rxd1 21.Kxd1 Rd7+ 22.Ke2 Kd8 23.Rb4 f5 24.Rh4 f6 25.Rh6 Rf7 26.c4 Ke7 27.Rh3 Kd6 28.b4 Rg7 29.Rh6 Rxg2 30.Rxh7 Rg4 31.Kd3 Kc6 32.Re7 Re4 33.f3 Rf4 34.Rxe6+ Kd7 35.Rxf6 Rxf3+ 36.Kd4 Rh3 37.Kc5 Kc7 38.Rf7+ Kb8 39.Kb6 Rh6+ 40.Ka5 Rxh2 41.c5 Rh6 42.a4 Rc6 43.Rxf5 Ka7 44.Rf7 Rc8 45.Rf5 Rc6 46.Rd5 Re6 47.b5 axb5 48.Kxb5 Re1 49.Rd4 Rc1 50.Kb4 b6 1/2-1/2
[Event `"`Trophée Ernst & Young 2007, Simultanée`"`]
[Site `"`Palais du Luxembourg, Paris`"`]
[Date `"`2007.03.11`"`]
[White `"`Vachier-Lagrave, Maxime`"`]
[Black `"`Polytech. Lille I`"`]
[Result `"`1-0`"`]
[WhiteElo `"`2573`"`]
[BlackElo `"`2158`"`]
1.e4 c5 2. Nf3 Nc6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 e5 6. Ndb5 d6 7. Bg5 a6 8. Na3 b5 9. Nd5 Be7 10. Bxf6 Bxf6 11. c4 b4 12. Nc2 a5 13. g3 Bg5 14. h4 Bh6 15. Bh3 O-O 16. Bxc8 Rxc8 17. b3 Ne7 18. Nce3 Bxe3 19. Nxe3 f5 20. exf5 Nxf5 21. Nxf5 Rxf5 22. Qd5+ Kh8 23. Rd1 Qb6 24. O-O Rf6 25. Kg2 Rcf8 26. f3 h6 27. Rd3 Qa6 28. Rfd1 a4 29. Qb5 Qxb5 30. cxb5 e4 31. fxe4 Rf2+ 32. Kh3 Rxa2 33. bxa4 Rff2 34. Kg4 Rxa4 35. Rb3 Ra3 36. Rdb1 Kh7 37. b6 Ra5 38. b7 h5+ 39. Kh3 Raa2 40. R1b2 Raxb2 41. Rxb2 Rf8 42. Rxb4 Rb8 43. Kg2 Kg6 44. Kf3 Kf7 45. Ke3 g6 46. Kd4 Ke6 47. Rb6 Kd7 48. Kd5 Kc7 49. Rb1 Kd7 50. Rb2 Kc7 51. Ke6 Re8+ 52. Kf7 1-0
[Event `"`5th Open`"`]
[Site `"`La Fere FRA`"`]
[Round `"`9`"`]
[Date `"`2006.07.14`"`]
[White `"`Deneuville, Ludovic`"`]
[Black `"`Godart, Francois`"`]
[WhiteElo `"`2009`"`]
[BlackElo `"`1952`"`]
[Result `"`1-0`"`]
1.e4 c6 2.d3 d5 3.Nd2 g6 4.Ngf3 Bg7 5.g3 e5 6.Bg2 Ne7 7.O-O O-O 8.c3 b6 9.Re1 d4 10.c4 c5 11.h3 Nbc6 12.Nf1 a6 13.Bd2 b5 14.Qc1 Qd6 15.b3 Be6 16.Ng5 b4 17.f4 f6 18.Nxe6 Qxe6 19.Nh2 a5 20.Rf1 a4 21.f5 Qd7 22.h4 Ra6 23.Bh6 Rfa8 24.Bxg7 Kxg7 25.Rb1 axb3 26.axb3 Qa7 27.Ng4 Ng8 28.Bh3 Ra2 29.fxg6 hxg6 30.Rxf6 Nxf6 31.Qh6+ Kf7 32.Rf1 Ra1 33.Qh7+ Ke6 34.Nxf6+ Kd6 35.Ne8+ Rxe8 36.Qxg6+ Ke7 37.Qf6# 1-0
[Event `"`5th Open`"`]
[Site `"`La Fere FRA`"`]
[Round `"`6`"`]
[Date `"`2006.07.12`"`]
[White `"`Feryn, Benjamin`"`]
[Black `"`Deneuville, Ludovic`"`]
[WhiteElo `"`1853`"`]
[BlackElo `"`2009`"`]
[Result `"`0-1`"`]
1.e4 e5 2.Nc3 Nf6 3.Bc4 Nc6 4.d3 d6 5.Nge2 Be6 6.Bb5 a6 7.Ba4 d5 8.Ng3 Bb4 9.Bg5 h6 10.Bd2 O-O 11.O-O Bc5 12.Re1 Ng4 13.Rf1 Qh4 14.h3 Nxf2 15.Rxf2 Qxg3 16.Qe2 Bxh3 17.Qf3 Qxf3 18.gxf3 Bxf2+ 19.Kxf2 dxe4 20.Nxe4 Bf5 21.Ng3 Bg6 22.Re1 f6 23.Rg1 Kh7 24.Ne4 b5 25.Bb3 Nd4 26.Bb4 Rfe8 27.Nc5 a5 28.Bc3 a4 29.Bd5 c6 30.Bxd4 cxd5 31.Be3 Rac8 0-1
[Event `"`5th Open`"`]
[Site `"`La Fere FRA`"`]
[Round `"`5`"`]
[Date `"`2006.07.11`"`]
[White `"`Deneuville, Ludovic`"`]
[Black `"`Lombard, Christophe`"`]
[WhiteElo `"`2009`"`]
[BlackElo `"`1797`"`]
[Result `"`1-0`"`]
1.e4 e5 2.Bc4 Nf6 3.Nf3 c6 4.Nxe5 Qe7 5.d4 Nxe4 6.Bxf7+ Kd8 7.Bb3 d5 8.f3 Qh4+ 9.g3 Qf6 10.fxe4 Bb4+ 11.c3 Rf8 12.Qe2 1-0
[Event `"`Trophée Ernst & Young 2006, Simultanée`"`]
[Site `"`Palais du Luxembourg, Paris`"`]
[Date `"`2006.05.14`"`]
[White `"`Kramnik, Vladimir`"`]
[Black `"`Polytech'Lille`"`]
[Result `"`1-0`"`]
[WhiteElo `"`2741`"`]
[BlackElo `"`2149`"`]
1.d4 Nf6 2. c4 e6 3. Nf3 b6 4. g3 Ba6 5. b3 Bb4+ 6. Bd2 Be7 7. Bg2 c6 8. Bc3 d5 9. Ne5 Nfd7 10. Nxd7 Nxd7 11. Nd2 O-O 12. O-O Rc8 13. Re1 b5 14. c5 e5 15. e3 e4 16. a4 Qc7 17. Bf1 Rb8 18. b4 f5 19. Ra3 Bc8 20. axb5 cxb5 21. Qa1 a6 22. Rxa6 Bxa6 23. Qxa6 Rf6 24. Qa2 Qb7 25. Ra1 g5 26. Bb2 Nf8 27. Nb1 Ne6 28. Nc3 Nc7 29. Bxb5 Nxb5 30. Nxd5 Kf8 31. Nxf6 Bxf6 32. Qe6 Kg7 33. Ra6 Qf7 34. Qxf5 Nc7 35. Rd6 Rxb4 36. Rd7 Be7 37. Qe5+ Qf6 38. Rxe7+ Kg6 39. Qxe4+ Qf5 40. Rg7+ 1-0
</ct-pgn-viewer>



Chess viewer powered by <a href="https://chesstempo.com" target="_blank">https://chesstempo.com</a>
